### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by diuchouni** [xxxxue/Autojs_Rhino_Dex_Self#2]
![image](https://github.com/xxxxue/Autojs_Rhino_Dex/assets/97949901/3b57559e-20a9-466c-b32b-ffc9a0d1eb5b)

**Comment by xxxxue** [comment]
我从 release 里面下载了一个 jar , 执行后没有复现出你的截图上的问题

执行截图
![image](https://github.com/xxxxue/Autojs_Rhino_Dex/assets/32764266/0c119aea-21a8-4153-8ee9-64b71247179a)

我的 java 环境是 Oracle JDK 8
![image](https://github.com/xxxxue/Autojs_Rhino_Dex/assets/32764266/88d83e39-6ed0-4c68-a7f1-560067a752e9)
