### ISSUE TITLE
当转换的js代码文件比较大的时候，报错generated bytecode for method exceeds 64K limit.

### ISSUE THREAD

**Issue by vipterry** [xxxxue/Autojs_Rhino_Dex_Self#4]
输入文件：dist/apps/script.js
输出文件夹：dist/apps/
最终的输出地址:dist/apps/20240605_133246
Rhino 优化等级:0
禁用字符串加密:false

Exception in thread "main" org.mozilla.classfile.ClassFileWriter$ClassFileFormatException: generated bytecode for method exceeds 64K limit.
	at org.mozilla.classfile.ClassFileWriter.stopMethod(ClassFileWriter.java:310)
	at org.mozilla.javascript.optimizer.Codegen.generateFunctionConstructor(Codegen.java:681)
	at org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:264)
	at org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:176)
	at org.mozilla.javascript.optimizer.ClassCompiler.compileToClassFiles(ClassCompiler.java:161)
	at org.mozilla.mycode.Main.toDexFile(Main.java:96)
	at org.mozilla.mycode.Main.main(Main.java:73)

<img width="716" alt="image" src="https://github.com/xxxxue/Autojs_Rhino_Dex/assets/7145196/1e64d907-46e1-49c1-96c1-1e72ef8dc9ef">

**Comment by xxxxue** [comment]
搜索引擎看了下.  这里有个方案..  你可以试一试, 
命令中 优化等级改为 -1
 `-l -1`

https://blog.csdn.net/freishlove/article/details/83803439

**Comment by vipterry** [comment]
> 搜索引擎看了下. 这里有个方案.. 你可以试一试, 命令中 优化等级改为 `-l -1`
> 
> https://blog.csdn.net/freishlove/article/details/83803439

这个文章我也看到了，但也是不行，这个js文件混淆过比较大，即使不混淆也要1百多k，还是不行。

<img width="712" alt="image" src="https://github.com/xxxxue/Autojs_Rhino_Dex/assets/7145196/efdb9272-45e7-47dd-9306-0f6f63d16847">

**Comment by xxxxue** [comment]
我这边的 js 文件是  260K
出来的 dex 500K
执行一切正常,


[pull](https://github.com/mozilla/rhino/pull/486)
[issues](https://github.com/mozilla/rhino/issues?q=generated+bytecode+for+method+exceeds+64K+limit.)

这个 64K 好像是 java 虚拟机中 的规则

你可以用排除法, 测试下哪个 js 方法 引起的这个问题
找到后, 把他拆成多个小方法, 

或者是 研究下把部分代码 dex . 不关键的代码还是保持 js

如果还是没有能执行成功.  那实在没法了. 
只能等 autox 的大佬, 把 Rhino 换成 nodejs, 
到时候用 nodejs 的加密方式

**Comment by vipterry** [comment]
> 时候用 nodejs 的加



> 我这边的 js 文件是 260K 出来的 dex 500K 执行一切正常,
> 
> [pull](https://github.com/mozilla/rhino/pull/486) [issues](https://github.com/mozilla/rhino/issues?q=generated+bytecode+for+method+exceeds+64K+limit.)
> 
> 这个 64K 好像是 java 虚拟机中 的规则
> 
> 你可以用排除法, 测试下哪个 js 方法 引起的这个问题 找到后, 把他拆成多个小方法,
> 
> 或者是 研究下把部分代码 dex . 不关键的代码还是保持 js
> 
> 如果还是没有能执行成功. 那实在没法了. 只能等 autox 的大佬, 把 Rhino 换成 nodejs, 到时候用 nodejs 的加密方式

从你给的链接上找过去，找到一个讨论，超大的js文件的确会有问题，应该会在未来的“rhino_1_8”的分支版本解决，如果方便的话能不能编译一个测试一下，或者等1.8版本的正式版出来再说。

<img width="1282" alt="image" src="https://github.com/xxxxue/Autojs_Rhino_Dex/assets/7145196/cd2ccbac-f01d-4792-bdc4-3e3a854f87bf">

**Comment by vipterry** [comment]
我尝试把“ rhino_1_8”分支的代码直接拿到我们这个项目上直接编译，好像已经不兼容，很多代码警告和错误（我完全不会写Java的），方便的话帮忙看一看。

<img width="588" alt="image" src="https://github.com/xxxxue/Autojs_Rhino_Dex/assets/7145196/9c92b31d-1a19-4038-8e99-024db3b50a7a">
<img width="635" alt="image" src="https://github.com/xxxxue/Autojs_Rhino_Dex/assets/7145196/d184b9f2-d904-42b5-956b-4e2d62d8b304">

**Comment by xxxxue** [comment]
> 我尝试把“ rhino_1_8”分支的代码直接拿到我们这个项目上直接编译，好像已经不兼容，很多代码警告和错误（我完全不会写Java的），方便的话帮忙看一看。
> 

这个分支太久了.  涉及多个文件新旧代码的合并 和 测试.   估计作者来了都搞不了. 
咱们搞不定这个

![K}~SEHDJY)}9%{@ $8275LF](https://github.com/xxxxue/Autojs_Rhino_Dex/assets/32764266/147e705d-e5a5-46de-b6d8-a1dd23a0bbe1)
